version: "3.7"

volumes:
  postgres_data: {}

services:
  api:
    build: ./api
    container_name: api
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - ./api:/api
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql